# Generated by Django 5.1.7 on 2025-07-09 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_rename_deptor_assignment_debtor'),
        ('portfolio', '0002_alter_portfolio_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Deptor',
            new_name='Debtor',
        ),
        migrations.RenameField(
            model_name='obligation',
            old_name='deptor',
            new_name='debtor',
        ),
    ]
