# Generated by Django 5.1.7 on 2025-07-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_rename_deptor_debtor_rename_deptor_obligation_debtor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='identification',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='number_phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='obligation',
            name='portfolio_type',
            field=models.CharField(choices=[('ADMINISTRATIVE', 'Administrative portfolio'), ('PRELEGAL', 'Pre-legal portfolio'), ('LEGAL', 'Legal portfolio')], default='ADMINISTRATIVE', max_length=20),
        ),
    ]
