# Generated by Django 5.1.7 on 2025-08-10 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_customuser_table'),
        ('portfolio', '0004_alter_debtor_identification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtor',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='debtors', to='account.tenant'),
        ),
    ]
