# Generated by Django 5.1.7 on 2025-07-07 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_customuser_table'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='tenants',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='tenant',
        ),
        migrations.AddField(
            model_name='client',
            name='tenant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='account.tenant'),
            preserve_default=False,
        ),
    ]
