# Generated by Django 5.1.7 on 2025-07-07 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_customuser_table'),
        ('client', '0002_remove_client_tenants_remove_contract_tenant_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('name', 'tenant')},
        ),
    ]
