# Generated by Django 5.1.7 on 2025-07-09 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='deptor',
            new_name='debtor',
        ),
    ]
